### ISSUE TITLE
Script throws "ps - pid must be a valid integer value" error and crashes

### ISSUE THREAD

**Issue by leonbohn** [Lee182/budgie-launcher-super#2]
I just installed the script and tried it from the command line by calling

> /usr/bin/budgie-launcher-super 1

which resulted in the following output:
> (node:13603) UnhandledPromiseRejectionWarning: Error: ps - pid must be a valid integer value
    at processPids (/usr/lib64/node_modules/budgie-launcher-super/node_modules/ps/lib/index.js:119:10)
    at lookup (/usr/lib64/node_modules/budgie-launcher-super/node_modules/ps/lib/index.js:23:35)
    at getWindows (/usr/lib64/node_modules/budgie-launcher-super/index.js:116:23)
(node:13603) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:13603) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Currently I am running a fresh install of Solus 4 Budgie.

**Comment by Lee182** [comment]
```javascript
  const sh1 = await sh(`wmctrl -lp`)
  const windows = sh1.stdout
    .trim()
    .split('\n')
    .map(line => {
      const items = line.split(/\s+/)
      return {
        hexWID: items[0],
        wid: parseInt(items[0], 16),
        desktop: items[1],
        pid: Number(items[2]),
        user: items[3],
        title: items.slice(4).join(' ')
      }
    })
  const procs = await ps({ pid: windows.map(o => o.pid) })
```

What do you get when you run `$ wmctrl -lp` in the terminal. It seems to be blowing up on the last line above.
It maybe because I made the script for manjaro community budgie edition. (Though I have distro hopped to deepinOS)

https://aur.archlinux.org/packages/nodejs-budgie-launcher-super/ 

You may need to install
dconf
wmctrl
xdotool
npm
nodejs >=10.10

Hope this helps.
